 [env:seeed_xiao_esp32s3]
platform = platformio/espressif32@6.10.0
board = seeed_xiao_esp32s3
framework = arduino
monitor_speed = 115200
upload_speed = 115200
upload_flags =
  --no-stub

lib_deps =
  sparkfun/SparkFun BNO08x Cortex Based IMU@1.0.6

build_flags =
  -D CAMERA_MODEL_XIAO_ESP32S3
  -D CORE_DEBUG_LEVEL=3

[env:imu_serial_debug]
extends = env:seeed_xiao_esp32s3
build_flags =
  ${env:seeed_xiao_esp32s3.build_flags}
  -D IMU_SERIAL_DEBUG_MODE

[env:zenoh_stream]
extends = env:seeed_xiao_esp32s3
lib_deps =
  ${env:seeed_xiao_esp32s3.lib_deps}
  https://github.com/eclipse-zenoh/zenoh-pico.git#1.9.0
build_flags =
  ${env:seeed_xiao_esp32s3.build_flags}
  -D ZENOH_STREAM_MODE
